..\release\zma.exe test1.asm test1.asm.bin
move zma.log test1.asm.log
..\release\zma.exe test2.asm test2.asm.bin
move zma.log test2.asm.log
..\release\zma.exe test3.asm test3.asm.bin
move zma.log test3.asm.log
..\release\zma.exe test4.asm test4.asm.bin
move zma.log test4.asm.log
..\release\zma.exe test5.asm test5.asm.bin
move zma.log test5.asm.log
..\release\zma.exe test6.asm test6.asm.bin
move zma.log test6.asm.log
..\release\zma.exe test7.asm test7.asm.bin
move zma.log test7.asm.log
..\release\zma.exe test8.asm test8.asm.bin
move zma.log test8.asm.log
..\release\zma.exe test9.asm test9.asm.bin
move zma.log test9.asm.log
..\release\zma.exe test10.asm test10.asm.bin
move zma.log test10.asm.log
pause
